name = "App-ansicolumn"
readme_from = "script/ansicolumn"
badges = ["travis-ci.com"]
authority="cpan:UTASHIRO"

module_maker="ModuleBuildTiny"
static_install = "auto"

[release]
do_not_upload_to_cpan = true
